### ISSUE TITLE
Processing3.0.2 compatibility

### ISSUE THREAD

**Issue by arcoyk** [danbernier/WordCram#67]
This happens as another libraries, but "super-easy" installation won't work well on Processing3.0.2. Not sure why but maybe something in directory name rules?

**Comment by danbernier** [comment]
Could you clarify what you mean? I'm running Processing 3.2.1 right now, and it installs & runs ok, and while I don't remember v3.0.2 specifically, I'm pretty sure I've been able to install & run it for all recent versions (though I don't make as many WordCrams these days as I used to).

If you mean you can't install it through the Sketch > Import Library... > Add Library... dialog box, that's because I haven't yet submitted WordCram to the Processing organizers - in effect, they don't know WordCram exists.

**Comment by danbernier** [comment]
Closing, since I still haven't had trouble with Processing 3.*.
